### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by DarkmatterVale** [cortical-io/python-client-sdk#8]
Do you have any examples for how to use the library?

I would like to use this library to compare two text statements, but it is not clear how to accomplish this.

Thanks for the help,
Vale Tolpegin

**Comment by neiltipper** [comment]
Hi Vale

There are some simple examples in the test classes. 
An example of comparing 2 texts can be found in: python-client-sdk/tests/unit/testCompareApi.py

You'll also need to edit the file python-client-sdk/tests/unit/testConfiguration.py and put in your api-key.


Thanks for the question. 
Regards,
Cortical.io team

**Comment by rhyolight** [comment]
I've had the same problem using this client library. I could not figure out how to use it, and the test cases are not that illuminating. I think it would be a great addition to add some documentation so that people can understand the typical skeleton code required. Perhaps even a sample script that does something interesting and fetches an API key from an environment variable?

**Comment by neiltipper** [comment]
Great suggestion. I'll add this to our backlog.

**Comment by DarkmatterVale** [comment]
Awesome. Thank you!
